#!/usr/bin/python3

# Generate a C++ variable of an array of key

import re
from pathlib import Path

def main():
    current_file_dir = Path(__file__).parent.resolve()
    source = current_file_dir / "../sorted_scan_codes.txt"

    key_names = []
    key_events = []
    with open(source) as f:
        for index, line in enumerate(f.readlines()):
            key_name, key_status = re.findall(r"\t(.*) (pressed|released)", line)[0]
            if key_name not in key_names:
                key_names.append(key_name)
            key_id = key_names.index(key_name)
            is_pressed = True if key_status == "pressed" else False
            # print(hex(key_id), key_name, is_pressed)
            # keyevent_id, key_id, key_name, key_status
            key_events.append((index, key_id, key_name, is_pressed))

        # for index, name in enumerate(key_names):
            # print(hex(index), name)
    keyevent_table = current_file_dir / "keyevent_table.cpp"
    with open(keyevent_table, "w") as f:
        f.write("// generated by codegen_key_table.py\n")
        f.write("// data source: sorted_scan_codes.txt\n")
        f.write("\n\n")
        f.write("// cd Project root\n")
        f.write("// python3 src/codegen_key_table.py")
        f.write("\n\n")
        f.write("#include \"kernel.h\"\n")
        f.write("KeyboardKey Key_table[] = {\n")
        for index, name in enumerate(key_names):
            if name == "\\":
                # single \ to double \
                name = "\\\\"
            if name == "\"apps\"":
                name = "\\\"apps\\\""
            f.write(f"    {{ {hex(index)}, \"{name}\" }},\n")
        f.write("};")
        f.write("\n\n")

        f.write("KeyEvent Keyevent_table[] = {\n")
        for index, (event_id, key_id, key_name, is_pressed) in enumerate(key_events):
            status = "true" if is_pressed else "false"
            if key_name == "\\":
                # single \ to double \
                key_name = "\\\\"
            if key_name == "\"apps\"":
                key_name = "\\\"apps\\\""
            f.write(f"    {{ {hex(event_id)}, {hex(key_id)}, \"{key_name}\", {status} }},\n")
        f.write("};")
        f.write("\n\n")


if __name__ == "__main__":
    main()